### ISSUE TITLE
Deploy doesn't trigger on article update

### ISSUE THREAD

**Issue by robinmetral** [iamtimsmith/wp-trigger-netlify-build#2]
Hey @iamtimsmith, I've stumbled on this plugin from your Gatsby and WordPress series. Thanks for building it!

I've successfully installed it on my WordPress endpoint and configurated my Netlify hook & status links.

However I've tried to update one of my existing articles, but the build wasn't triggered on the Netlify endpoint.

Am I doing it wrong?

**Comment by iamtimsmith** [comment]
@robinmetral What are you putting in for your settings within the WordPress admin?

**Comment by robinmetral** [comment]
Thanks for your blazing fast reply :wink: 

I'm using the URL from my Netlify site settings (I created a hook), which looks like this in the console:

![netlify-console-screenshot-with-hook-url](https://user-images.githubusercontent.com/35560568/57467145-4cb8b880-7282-11e9-9b1f-e938435ef253.png)

(the end of the endpoint is cropped)

And I'm using the image URL and status URL for the Netlify status badge. I think these are OK, they're for status not for triggering the build, right?

**Comment by robinmetral** [comment]
There might be a small bug: I've been getting this update on my Admin panel since I updated the plugin settings. It's not going away, even after signing out and in again.

![wordpress-admin-screenshot-saying-your-settings-have-been-updated](https://user-images.githubusercontent.com/35560568/57467453-e6806580-7282-11e9-860b-50b27c43bfea.png)

**Comment by iamtimsmith** [comment]
@robinmetral No, the statuses shouldn't have any bearing on the build. I'll take a look into that message and see if I can figure out what's going on.

**Comment by robinmetral** [comment]
Thanks a lot @iamtimsmith! Let me know if I can do anything to help (although I'm not very familiar with the WordPress ecosystem).

Also I just made sure that my hook works with a `curl` request from my CLI: it does :heavy_check_mark:

**Comment by re1** [comment]
It seems like I am having the same issue here. I too followed all instructions and curl works as excepted.

**Comment by robinmetral** [comment]
Thanks @re1, good to know this was reproduced

**Comment by iamtimsmith** [comment]
@robinmetral @re1 Okay, so I've been looking into this. As far as the notice is concerned, this is a problem within WordPress so this will take some work to function as expected.

I did a fresh install in a local docker environment, pasted in the webhook URL and the urls for badge and link. I'm seeing it trigger a build when I update a blog post. While it fails (I think because it's a local docker environment), it does trigger the build. My followup questions are:

- Are you seeing it fail or not seeing it trigger anything at all?
- Are you updating blog posts, pages, or a custom content type?

**Comment by robinmetral** [comment]
Thanks @iamtimsmith for looking into this!

When I first opened this issue, updating a blog post didn't trigger anything (no error message, nothing).

BUT I tested things again today and:

- Updating a page triggered a build :tada: 
- Updating a post triggered a build :tada:

So as far as I'm concerned, this issue is solved. I'm thinking it might have been the hooks taking some time to get set up on either the WordPres or Netlify end.

The only problem that remains for me is this:

> I've been getting this update on my Admin panel since I updated the plugin settings. It's not going away, even after signing out and in again.
> 
> ![wordpress-admin-screenshot-saying-your-settings-have-been-updated](https://user-images.githubusercontent.com/35560568/57467453-e6806580-7282-11e9-860b-50b27c43bfea.png)

I'm still getting this message at all times, where I think I should instead get notifications saying a build was triggered.

Do you want me to open a new issue for this?

**Comment by iamtimsmith** [comment]
Awesome! I'm glad it's working for you. @re1 Is this working for you now as well?

**Comment by re1** [comment]
Hi @iamtimsmith. Sadly it still does not work for me. I am running WordPress on latest version using the following docker compose file:
```
version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: ${WP_URL}
      LETSENCRYPT_HOST: ${WP_URL}
      LETSENCRYPT_EMAIL: ${WP_EMAIL}
    volumes:
      - ./wp-content:/var/www/html/wp-content/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-certs:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-certs:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy

volumes:
  db: {}
  nginx-certs: {}
  nginx-vhosts: {}
  nginx-html: {}
```
